name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm setup
        run: npm install -g npm@latest
      - name: Build and test
        run: |
          npm install
          npm run coverage
        env:
          CI: true
